baseURL = "https://rajat404.com/"
languageCode = "en-us"
title = "Rajat Goyal"
theme = "hello-friend-ng"
googleAnalytics = "UA-163911021-1"
disqusShortname = "rajat404"

# [taxonomies]
#   category = "blog"
#   tag      = "tags"
#   series   = "series"

[permalinks]
  posts = "/blog/:year/:month/:title/"

[author]
  name = "Rajat Goyal"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Personal Website & Blog"
  keywords = ""
  images = [""]

  homeSubtitle = "SciFi Nerd. Book Hoarder. Software Developer. Geek Extraordinaire"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = ""

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = true  # Set "text-align: justify" to .content.

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "blog"

  # Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor = "#252627"

  # Colors for favicons
  [params.favicon.color]
    mask = "#252627"
    msapplication = "#252627"
    theme = "#252627"

  [params.logo]
    logoText     = "$ cd /home"
    logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    # logoCursorDisabled = false
    # Set to a valid CSS color to change the cursor in the logo.
    # logoCursorColor    = "#67a2c9"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    # logoCursorAnimate  = "2s"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/rajat404"

  [[params.social]]
    name = "github"
    url  = "https://github.com/rajat404"

  [[params.social]]
    name = "instagram"
    url  = "https://instagram.com/rajat404"

  [[params.social]]
    name = "linkedin"
    url  = "https://in.linkedin.com/in/rajat404"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "blog/"
  [[menu.main]]
    identifier = "til"
    name       = "TIL"
    url        = "til/"
  [[menu.main]]
    identifier = "tools"
    name       = "Tools"
    url        = "tools/"
